# Generated by Django 4.2.5 on 2023-10-29 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desert_name', models.CharField(max_length=100, unique=True, verbose_name='desert name')),
                ('description_of_desert', models.TextField(max_length=500, verbose_name='description of desert')),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.CharField(max_length=100, unique=True, verbose_name='drink name')),
                ('description_of_drink', models.TextField(max_length=500, verbose_name='description of drink')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, unique=True, verbose_name='food name')),
                ('description_of_food', models.TextField(max_length=500, verbose_name='description of food')),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad_name', models.CharField(max_length=100, unique=True, verbose_name='salad name')),
                ('description_of_salad', models.TextField(max_length=500, verbose_name='description of salad')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deserts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.desert')),
                ('drinks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.drink')),
                ('foods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.food')),
                ('salads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.salad')),
            ],
        ),
    ]
