# Generated by Django 4.2.5 on 2023-10-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desert',
            name='price',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='drink',
            name='price',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='salad',
            name='price',
            field=models.IntegerField(default=15),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
