# Generated by Django 4.2.5 on 2023-10-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_desert_price_drink_price_food_price_salad_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=100)),
                ('drink', models.CharField(max_length=100)),
                ('salad', models.CharField(max_length=100)),
                ('desert', models.CharField(max_length=100)),
                ('total_price', models.IntegerField()),
            ],
        ),
    ]
