# Generated by Django 4.2.5 on 2023-10-31 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_sessions', '0006_tables_is_full'),
        ('menu', '0004_order_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='table_sessions.tables'),
        ),
    ]
