# Generated by Django 4.2.5 on 2023-10-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='table_password',
            field=models.CharField(default='00', max_length=10),
        ),
    ]
