# Generated by Django 4.2.5 on 2023-10-30 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_sessions', '0003_alter_tables_table_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tables',
        ),
    ]
