# Generated by Django 4.2.5 on 2023-10-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table_Numbers',
        ),
    ]
