# Generated by Django 4.2.5 on 2023-10-30 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0004_order_table_number'),
        ('table_sessions', '0006_tables_is_full'),
        ('supervisor', '0002_delete_table_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.order')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='table_sessions.tables')),
            ],
        ),
    ]
