# Generated by Django 4.2.5 on 2023-10-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantorders',
            name='table',
            field=models.CharField(max_length=10),
        ),
    ]
