# Generated by Django 4.2.5 on 2023-10-31 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_order_table_number'),
        ('supervisor', '0005_alter_instantorders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantorders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.order'),
        ),
    ]
